#!/usr/bin/env bash
# Build a FAT32 shuttle disk image from src/ and tests/.
# Generates Boot.ZC by enumerating tests/T_*.ZC in sorted order.
# macOS-specific: uses hdiutil + newfs_msdos.

set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
IMG="$REPO/build/shuttle.img"
# Even at 256 MB hdiutil's `-fs MS-DOS` defaults to FAT16, which mismatches
# the MBR partition entry's FAT32 type (0x0B) declaration and confuses
# ZealOS's cluster reader. We pass `-fs FAT32` explicitly below.
SIZE_MB=256
STAGE="$REPO/build/shuttle-stage"

mkdir -p "$REPO/build"

# 1. Stage everything that goes on the shuttle in one directory.
rm -rf "$STAGE"
mkdir -p "$STAGE"

# Copy src/*.ZC and tests/*.ZC into the stage.
shopt -s nullglob
for f in "$REPO"/src/*.ZC "$REPO"/tests/*.ZC; do
  [ -f "$f" ] || continue
  cp "$f" "$STAGE/"
done

# 2. Generate Boot.ZC from the test list.
{
  echo '// Boot.ZC — auto-generated by scripts/build-shuttle.sh.'
  echo '// Auto-included by ~/MakeHome.ZC after Setup.ZC has been run once.'
  echo ''
  echo '// Comm port API (CommInit8n1, CommPrint, CommPutS) is not auto-loaded'
  echo '// — pull it in from the system docs tree.'
  echo '#include "::/Doc/Comm";'
  echo ''
  echo 'CommInit8n1(1, 9600);'
  echo 'CommPrint(1, "TEST_RUN_BEGIN\n");'
  echo ''
  echo '#include "E:/Assert.ZC";'
  # T= filter: e.g. `make test T=Hello` only runs tests/T_Hello.ZC.
  # Bare substring match so `T=math` matches T_Math.ZC, T_MathX.ZC, etc.
  for f in "$REPO"/tests/T_*.ZC; do
    [ -f "$f" ] || continue
    base=$(basename "$f")
    if [ -n "${T:-}" ] && ! [[ "$base" == *"$T"* ]]; then
      continue
    fi
    echo "#include \"E:/$base\";"
  done
  echo ''
  echo 'TEST_SUMMARY;'
  echo 'CommPrint(1, "TEST_RUN_END\n");'
  echo ''
  echo '// No ACPI shutdown here — host-side run-tests.sh sends `quit` via'
  echo '// the QEMU monitor when it sees TEST_RUN_END. Spinning is enough.'
  echo 'while (TRUE) Sleep(1000);'
} > "$STAGE/Boot.ZC"

# 3. Detach any leftover mount of the previous image.
for dev in $(hdiutil info | awk -v img="$IMG" '$0 ~ img {print $1}'); do
  hdiutil detach -quiet "$dev" 2>/dev/null || true
done

# 4. Build the image using hdiutil with -layout MBRSPUD so the disk has a
# proper MBR partition table (single FAT32 partition). ZealOS's Mount auto-
# detect needs the partition table to find the filesystem at the right offset.
rm -f "$IMG"
TMPDMG="$REPO/build/shuttle.tmp.dmg"
rm -f "$TMPDMG"
hdiutil create -size "${SIZE_MB}m" -fs FAT32 -volname SHUTTLE \
  -layout MBRSPUD "${TMPDMG%.dmg}" >/dev/null

# 5. Mount and copy stage contents in.
MNT=$(mktemp -d)
hdiutil attach -mountpoint "$MNT" "$TMPDMG" >/dev/null
trap 'hdiutil detach -quiet "$MNT" 2>/dev/null || true; rmdir "$MNT" 2>/dev/null || true; rm -f "$TMPDMG"' EXIT

cp "$STAGE"/* "$MNT/"

echo "==> shuttle contents:"
ls -la "$MNT" | awk 'NR>1 && $NF !~ /^\./ {printf "    %s  %s\n", $5, $NF}'

hdiutil detach -quiet "$MNT"
rmdir "$MNT"

# 6. The .dmg from hdiutil is already a raw UDRW image, just rename to .img.
mv "$TMPDMG" "$IMG"
trap - EXIT

echo "==> built $IMG ($(du -h "$IMG" | cut -f1))"
