#!/usr/bin/env bash
# Build a FAT32 shuttle disk image from src/ and tests/.
# Generates Boot.ZC by enumerating tests/T_*.ZC in sorted order.
# macOS-specific: uses hdiutil + newfs_msdos.

set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
IMG="$REPO/build/shuttle.img"
# Even at 256 MB hdiutil's `-fs MS-DOS` defaults to FAT16, which mismatches
# the MBR partition entry's FAT32 type (0x0B) declaration and confuses
# ZealOS's cluster reader. We pass `-fs FAT32` explicitly below.
SIZE_MB=256
STAGE="$REPO/build/shuttle-stage"

mkdir -p "$REPO/build"

# 1. Stage everything that goes on the shuttle in one directory.
rm -rf "$STAGE"
mkdir -p "$STAGE"

# Copy src/*.ZC and tests/*.ZC into the stage.
shopt -s nullglob
for f in "$REPO"/src/*.ZC "$REPO"/tests/*.ZC; do
  [ -f "$f" ] || continue
  cp "$f" "$STAGE/"
done

# 2. Generate Boot.ZC from the test list.
{
  echo '// Boot.ZC — auto-generated by scripts/build-shuttle.sh.'
  echo '// Auto-included by ~/MakeHome.ZC after Setup.ZC has been run once.'
  echo ''
  echo '// Comm port API (CommInit8n1, CommPrint, CommPutS) is not auto-loaded'
  echo '// — pull it in from the system docs tree.'
  echo '#include "::/Doc/Comm";'
  echo ''
  echo 'CommInit8n1(1, 9600);'
  echo 'CommPrint(1, "TEST_RUN_BEGIN\n");'
  echo ''
  echo '#include "E:/Assert.ZC";'
  # T= filter: e.g. `make test T=Hello` only runs tests/T_Hello.ZC.
  # Bare substring match so `T=math` matches T_Math.ZC, T_MathX.ZC, etc.
  for f in "$REPO"/tests/T_*.ZC; do
    [ -f "$f" ] || continue
    base=$(basename "$f")
    if [ -n "${T:-}" ] && ! [[ "$base" == *"$T"* ]]; then
      continue
    fi
    echo "#include \"E:/$base\";"
  done
  echo ''
  echo 'TEST_SUMMARY;'
  echo 'CommPrint(1, "TEST_RUN_END\n");'
  echo ''
  # DAEMON=1 wires the live REPL. We must defer the daemon spawn to
  # post-boot context, otherwise the boot-phase parser quirks (NOTES.md)
  # apply when the queued source is parsed. The trick:
  #
  #   - Sys() can NOT be used directly: when called from sys_task during
  #     boot, Sys() runs JobsHandler synchronously, parsing the queued
  #     source IMMEDIATELY in boot phase — same quirks.
  #   - TaskExe(..., flags=0) queues the job WITHOUT triggering
  #     JobsHandler. The job sits in sys_task's wait queue until
  #     post-boot, where it gets parsed normally.
  #   - We must NOT terminate Boot.ZC with `while (TRUE) Sleep(...)`,
  #     because that pins sys_task in the spinner and the queue never
  #     drains. Letting Boot.ZC return naturally lets sys_task move on
  #     and process the queue. (run-tests.sh quits via the monitor
  #     socket when it sees TEST_RUN_END — no spinner needed.)
  if [ "${DAEMON:-0}" = "1" ]; then
    echo '// DAEMON=1: live REPL on COM2 (build/com2.sock).'
    echo '#include "E:/Daemon.ZC";'
    echo 'TaskExe(sys_task, Fs, "Spawn(&RunDaemon, NULL, \"Daemon\");", 0);'
    echo ''
  fi
  echo '// Boot.ZC ends here. sys_task drains its queue post-boot. The'
  echo '// host-side run-tests.sh quits qemu via the monitor socket when'
  echo '// it sees TEST_RUN_END, so no spinner is needed here.'
} > "$STAGE/Boot.ZC"

# 3. Detach any leftover mount of the previous image.
for dev in $(hdiutil info | awk -v img="$IMG" '$0 ~ img {print $1}'); do
  hdiutil detach -quiet "$dev" 2>/dev/null || true
done

# 4. Build the image using hdiutil with -layout MBRSPUD so the disk has a
# proper MBR partition table (single FAT32 partition). ZealOS's Mount auto-
# detect needs the partition table to find the filesystem at the right offset.
rm -f "$IMG"
TMPDMG="$REPO/build/shuttle.tmp.dmg"
rm -f "$TMPDMG"
hdiutil create -size "${SIZE_MB}m" -fs FAT32 -volname SHUTTLE \
  -layout MBRSPUD "${TMPDMG%.dmg}" >/dev/null

# 5. Mount and copy stage contents in.
MNT=$(mktemp -d)
hdiutil attach -mountpoint "$MNT" "$TMPDMG" >/dev/null
trap 'hdiutil detach -quiet "$MNT" 2>/dev/null || true; rmdir "$MNT" 2>/dev/null || true; rm -f "$TMPDMG"' EXIT

cp "$STAGE"/* "$MNT/"

echo "==> shuttle contents:"
ls -la "$MNT" | awk 'NR>1 && $NF !~ /^\./ {printf "    %s  %s\n", $5, $NF}'

hdiutil detach -quiet "$MNT"
rmdir "$MNT"

# 6. The .dmg from hdiutil is already a raw UDRW image, just rename to .img.
mv "$TMPDMG" "$IMG"
trap - EXIT

echo "==> built $IMG ($(du -h "$IMG" | cut -f1))"
